package com.kt.gitproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dat implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String anme;

	public dat() {
	}

	public java.lang.String getAnme() {
		return this.anme;
	}

	public void setAnme(java.lang.String anme) {
		this.anme = anme;
	}

	public dat(java.lang.String anme) {
		this.anme = anme;
	}

}